### PR TITLE
if you want.

### PR DESCRIPTION
**Pull request by glowsoony**
xml like.

### CODE REVIEW

**Comment by MemeHoovy** [comment]
totally didn't steal hscript from Wednesdays infidelity :trollface:

**Comment by glowsoony** [comment]
> totally didn't steal hscript from Wednesdays infidelity :trollface:

HEY HEY BRO THIS EVENTS ARE UNHARDCODED this way easier events but yes XDDDDDD

**Comment by BoloVEVO** [comment]
> totally didn't steal hscript from Wednesdays infidelity :trollface:

Fatherless act, but seems good to have hscript support in this abandoned fork.

**Comment by MemeHoovy** [comment]
> > totally didn't steal hscript from Wednesdays infidelity :trollface:
> 
> Fatherless act, but looks good to have hscript support in this abandoned fork.

wait what?

**Comment by glowsoony** [comment]
> > totally didn't steal hscript from Wednesdays infidelity :trollface:
> 
> Fatherless act, but looks good to have hscript support in this abandoned fork.

**Comment by BoloVEVO** [comment]
mf just missclicked and closed the pr.

**Pull request closed without merging**
