### PR TITLE
you know I fucking hate you and your ways right?

### PR DESCRIPTION
**Pull request by glowsoony**
well no really.

### CODE REVIEW

**Comment by BoloVEVO** [comment]
Why u hate me 😭.

**Comment by glowsoony** [comment]
> Why u hate me 😭.

it's just a joke

**Comment by MAJigsaw77** [comment]
That person isn't made to take command's from freaks like you

**Comment by glowsoony** [comment]
> That person isn't made to take command's from freaks like you

ok first I was just joking with the title, second he asked for me too make the pull for the crash handler and still hasn't merged it (even tho he asked for it)

**Comment by MAJigsaw77** [comment]
K

**Pull request merged**
