### PR TITLE
HScript Support.

### PR DESCRIPTION
**Pull request by glowsoony**
BRO SO GAY.

### CODE REVIEW

**Comment by TheRealJake12** [comment]
looks really cool. I dont know shit about this but I tried to add a dad variable. I dont think it worked + you should add it anyway

**Comment by TheRealJake12** [comment]
also an example script would be amazing :)

**Comment by TheRealJake12** [comment]
really cool. Add more variables.

**Comment by glowsoony** [comment]
> really cool. Add more variables.

I was going to but..really not needed as ever event that can be made in those scripts is unlimited (unless you don't know how to use it)

**Comment by glowsoony** [comment]
an event using the script: https://streamable.com/z26vm4

**Comment by TheRealJake12** [comment]
wait so it would be `PlayState.dad` and it would just work??

**Comment by glowsoony** [comment]
> wait so it would be `PlayState.dad` and it would just work??

yea

**Comment by glowsoony** [comment]
also another usage of scripts is not only for mid-song events like cam shake or fading or playstate stuff but also stage, notes, and other stuff. like in this example: 
image

**Comment by TheRealJake12** [comment]
now do one for goodNoteHit 

epicttrooll

**Comment by BoloVEVO** [comment]
I'll keep this pull request open to make changes until it's ready to be merged.

**Comment by glowsoony** [comment]
> I'll keep this pull request open to make changes until it's ready to be merged.

keep it open for 1 month and let's all see how this works out (after 1 month if it's ready merge!)

**Comment by glowsoony** [comment]
> now do one for goodNoteHit
> 
> epicttrooll

sure why not?

**Comment by TheRealJake12** [comment]
stage variables dont work. atleast for me anyway. I tweaked it to be just stepHit btw
image

**Comment by glowsoony** [comment]
> stage variables dont work. atleast for me anyway. I tweaked it to be just stepHit btw image

but what "bg" are when talking about??????

**Comment by TheRealJake12** [comment]
figured it would be smth like that. alr I'll test later

**Comment by TheRealJake12** [comment]
now make it work with modcore. (from what I'm seeing, it doesnt work. iirc the same happens with lua modcharts and modcore)

**Comment by BoloVEVO** [comment]
Modcore gives too many issues for softcoding. I think I'll remade the mod system with FileSystem as Psych.

**Comment by TheRealJake12** [comment]
> Modcore gives too many issues for softcoding. I think I'll remake the mod system with FileSystem as Psych.

try and use hscript instead of focusing on lua. Just use the FileSystem for scanning mods

**Comment by BoloVEVO** [comment]
> > Modcore gives too many issues for softcoding. I think I'll remake the mod system with FileSystem as Psych.
> 
> try and use hscript instead of focusing on lua. Just use the FileSystem for scanning mods

I'll just change the way the game detects the mods, hscript will be still in use.

**Comment by TheRealJake12** [comment]
epic

**Comment by BoloVEVO** [comment]
@glowsoony sync the branch with my latest commit I'm gonna test this pr.

**Comment by TheRealJake12** [comment]
now make a tutorial on how to move the notes (strum and all)

**Comment by glowsoony** [comment]
> now make a tutorial on how to move the notes (strum and all)

oh nah-

**Comment by TheRealJake12** [comment]
well then how would you make it tween the angle or alpha? doing the createTween or normal tween doesnt do shit

**Comment by glowsoony** [comment]
> well then how would you make it tween the angle or alpha? doing the createTween or normal tween doesnt do shit

that's why I have extra back up for that like New Var tweens but Bolo won't want to use them that's why I won't add them here.

**Comment by TheRealJake12** [comment]
a I was tryna call the function from playstate without setting the vars
also. **How make the note bois move??**

**Comment by glowsoony** [comment]
> a I was tryna call the function from playstate without setting the vars also. **How make the note bois move??**

**Comment by glowsoony** [comment]
> a I was tryna call the function from playstate without setting the vars also. **How make the note bois move??**

image

**Comment by TheRealJake12** [comment]
FlxEaseByString???

**Comment by glowsoony** [comment]
> FlxEaseByString???

?

**Comment by TheRealJake12** [comment]
big_trollge

**Comment by TheRealJake12** [comment]
image
would this work? the notes dont move at all

**Comment by TheRealJake12** [comment]
image
the variables

**Review by Luisinhi010 — APPROVED** [review]

**Comment by Wither362** [comment]
> > a I was tryna call the function from playstate without setting the vars also. **How make the note bois move??**
> 
> image

That code is wrong, from the `//mf altogether [player]` to the end

**Comment by glowsoony** [comment]
> > > a I was tryna call the function from playstate without setting the vars also. **How make the note bois move??**
> > 
> > 
> > image
> 
> That code is wrong, from the `//mf altogether [player]` to the end

ah but ofc let me remove that now

**Comment by BoloVEVO** [comment]
Closing until most of 1.5 features are pushed in the repo.

**Pull request closed without merging**
